version: "3.9"

services:
  web:
    image: test_task:latest
    container_name: test_task_container
    env_file:
      - .env
    command:
      - python test_endpoint/manage.py makemigrations
      - python test_endpoint/manage.py migrate
      - python test_endpoint/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"